name: PR API Trigger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Construct and Send API Request
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO_URL="${{ github.event.repository.url }}"
          FULL_URL="${REPO_URL}/pulls/${PR_NUMBER}/files"
          
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"url\": \"${FULL_URL}\"}" \
          https://varying-selle-harshkvr7-org-5796a877.koyeb.app/api/pr
